[package]
name = "biliup-bin"
version = "0.1.11"
edition = "2021"
description = "Upload video to bilibili."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
path = "src/main.rs"
name = "biliup"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glob = "0.3.0"
tokio = { version = "1", features = ["full"] }
stream-gears = {path="../stream-gears"}
biliup = {path="../biliup"}
bytes = "1.1.0"
qrcode = "0.12.0"
indicatif = "0.17.0-rc"
image = "0.23.14"
futures = "0.3.17"
dialoguer = "0.9.0"

[target.'cfg(any(all(target_arch="aarch64", target_vendor="unknown", target_os="linux"), target_env="musl"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }

[target.'cfg(not(any(all(target_arch="aarch64", target_vendor="unknown", target_os="linux"), target_env="musl")))'.dependencies]
reqwest = { version = "0.11", features = ["stream", "json"] }