line: kodo

streamers:
  视频patterns1*:
    copyright: 1
    source: 转载来源
    tid: 171 # 投稿分区
    cover: "" # 视频封面
    title: 标题
    desc_format_id: 0
    desc: 简介
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: ""
    dtime: ~
    open_subtitle: false
  视频patterns2*:
    copyright: 1
    source: 转载来源
    tid: 171 # 投稿分区
    cover: /cover/up.jpg # 视频封面
    title: 标题
    desc_format_id: 0
    desc: 简介
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: ""
    dtime: ~
    open_subtitle: false