[package]
name = "stream-gears"
version = "0.1.11"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "stream_gears"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }
biliup = { path = "../biliup" }
reqwest = { version = "*", features = ["blocking", "deflate", "gzip"] }
url = "*"
m3u8-rs = "4.0.0"
nom = "7"
serde = "1"
serde_json = "1.0"
chrono = "0.4"
bytes = "1.1.0"
byteorder = "1.4.3"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
futures = "0.3.21"
